spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${URL}
    username: ${USRNAME}
    password: ${PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 3MB

client-app:
  url: http://localhost:4200

server-app:
  secret-key: ${SECRET_KEY}
  expiration: 86400000